config/routes.rb
NewBlog::Application.routes.draw do
  devise_for :users

  root :to => 'welcome#index'
  resources :articles
  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title, :description, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(params[:article])
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end  

  def show
    @article = Article.find(params[:id])
  end
  
  def index
  	@articles = current_user.articles
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    Article.find(params[:id]).destroy
    redirect_to articles_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>	
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>
		 
<p>
	<%= f.label :description %><br>
	<%= f.text_area :description , :rows=>3 %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>User_id</th>
    <th>Actions</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= current_user.email  %></td>
      <td><%= link_to 'Show',article_path(article)%></td>
      <td><%= link_to 'Edit',edit_article_path(article)%></td>
      <td ><%= button_to 'delete', article_path(article), method: :delete, :confirm => :"Are you sure" %> </td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Create New Article', new_article_path %></td> 
</p> 

app/views/articles/new.html.erb
<%= form_for @article do |f| %>	
 <% if @article.present? && @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
		 
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description , :rows=>3 %>
	</p>
	<p>
  	<%= f.submit %>
	</p>
<% end %>
<%= link_to "Show All Articles", articles_path %>

app/views/articles/show.html.erb
<p> This show the record Number <%= @article.id %> </p>
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Description:</strong>
	<%= @article.description %>
</p>

<%= link_to 'Show All Articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:DarkTurquoise">
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

 <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= button_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
  <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<table style="border:groove 3px black; border-collapse:collapse;">
  <tr>
    <th style ="padding:15px">user_email</th>
    <th style = "padding:6px">User_id</th>
    <th style = "padding:6px" colspan="6">Actions</th>
  </tr>
 
  <% @user.each do |user| %>
    <tr>
      <td style ="color:SaddleBrown;padding:5px"><%= user.email %></td>
      <td style ="color:MidnightBlue;padding:10px"><%= user.id %></td>
      <td style="padding:5px"><%= link_to 'Show', user_path(user) %></td>
      <td style="padding:5px"><%= link_to 'Edit', edit_user_path(user) %></td>
      <td style="padding:5px"><%= button_to 'delete', user_path(user), method: :delete, :confirm => :"Are you sure" %> </td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Create New Article', new_article_path %></td> 
</p>  

<%= current_user.id %> 

app/views/welcome/index.html.erb
<center> <h3> Welcome </h3> </center>
<center> <img src ="images.jpeg"> </center>
<%= link_to ' Create New Article', new_article_path %>
<%= link_to ' Show All Articles', articles_path %>  
<%= link_to 'Show All User',:controller => :users, :action => :index %>